# Generated by .github/workflows/release.yml — do not edit by hand.
class Argus < Formula
  desc "Capture what AI coding agents actually did, and export it as OTLP/JSON"
  homepage "https://github.com/boogy/argus"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boogy/argus/releases/download/v0.2.0/argus-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "b982336f1eded83cdd236b0ef50c81fcbf580f12fb01a59efa3d1cbeb6f6cf47"
    end
    on_intel do
      url "https://github.com/boogy/argus/releases/download/v0.2.0/argus-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "ac5bffe92efa36d4efb1abd7701272caf14b9750b6bdbb7d2a06ae6b5144e52b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boogy/argus/releases/download/v0.2.0/argus-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "98fa5b0351f186c199f344db1ea7e36b7a599066e4abc709e8637755b1935725"
    end
    on_intel do
      url "https://github.com/boogy/argus/releases/download/v0.2.0/argus-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "66938f4a414c337e75c3339ce94e733d8947d4d6a9edaedf48f6218cea3d418a"
    end
  end

  def install
    bin.install "argus"
  end

  test do
    assert_match "argus #{version}", shell_output("#{bin}/argus --version")
  end
end
