# Generated by .github/workflows/release.yml — do not edit by hand.
class Argus < Formula
  desc "Capture what AI coding agents actually did, and export it as OTLP/JSON"
  homepage "https://github.com/boogy/argus"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boogy/argus/releases/download/v0.5.0/argus-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "fb2bd6e673b90e9258806fa5209e0a09b85190c67f0a9a43408e515bfbd66b11"
    end
    on_intel do
      url "https://github.com/boogy/argus/releases/download/v0.5.0/argus-0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "41ffe1b79376ebdfcd2830a1a2f2644ab937a7571b5583b6bedd7b169878d52d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boogy/argus/releases/download/v0.5.0/argus-0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "bd673df3a4a077f321ad80ae18dc0e9c0a921c1e70009fe42f1d26c8eac1a13f"
    end
    on_intel do
      url "https://github.com/boogy/argus/releases/download/v0.5.0/argus-0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "fb2d7a38c7b7d3a91170d659d92677fa92cbe0540a22fdff197d770821076761"
    end
  end

  def install
    bin.install "argus"
  end

  test do
    assert_match "argus #{version}", shell_output("#{bin}/argus --version")
  end
end
